function greentripdata201601 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GREENTRIPDATA201601 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  GREENTRIPDATA201601 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  greentripdata201601 = importfile("C:\Users\KevinChng\OneDrive - Techsource Systems Pte Ltd\TechSource\Customer Visit\125 Dyson Su lim\Upload\DataSet\green_tripdata_2016-01.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Mar-2020 22:37:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VendorID", "lpep_pickup_datetime", "Lpep_dropoff_datetime", "Store_and_fwd_flag", "RateCodeID", "Pickup_longitude", "Pickup_latitude", "Dropoff_longitude", "Dropoff_latitude", "Passenger_count", "Trip_distance", "Fare_amount", "Extra", "MTA_tax", "Tip_amount", "Tolls_amount", "Ehail_fee", "improvement_surcharge", "Total_amount", "Payment_type", "Trip_type"];
opts.VariableTypes = ["double", "datetime", "datetime", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Store_and_fwd_flag", "Ehail_fee"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Store_and_fwd_flag", "Ehail_fee"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "lpep_pickup_datetime", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, "Lpep_dropoff_datetime", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
greentripdata201601 = readtable(filename, opts);

end